# Generated by Django 4.2.6 on 2023-11-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbs', models.FloatField()),
                ('protien', models.FloatField()),
                ('fat', models.FloatField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
