# Generated by Django 4.2.6 on 2023-11-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foody',
            new_name='Food',
        ),
    ]
